2024-07-27 05:15:06.854 WARNING fixture:conftest.py:60: Process started
2024-07-27 05:15:06.858 INFO fixture:conftest.py:61: Process ongoing..
2024-07-27 05:15:06.861 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.address`.
2024-07-27 05:15:06.863 DEBUG faker.factory:factory.py:95: Provider `faker.providers.address` has been localized to `en_US`.
2024-07-27 05:15:06.863 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.automotive`.
2024-07-27 05:15:06.865 DEBUG faker.factory:factory.py:95: Provider `faker.providers.automotive` has been localized to `en_US`.
2024-07-27 05:15:06.865 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.bank`.
2024-07-27 05:15:06.867 DEBUG faker.factory:factory.py:86: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2024-07-27 05:15:06.867 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.barcode`.
2024-07-27 05:15:06.867 DEBUG faker.factory:factory.py:95: Provider `faker.providers.barcode` has been localized to `en_US`.
2024-07-27 05:15:06.867 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.color`.
2024-07-27 05:15:06.868 DEBUG faker.factory:factory.py:95: Provider `faker.providers.color` has been localized to `en_US`.
2024-07-27 05:15:06.868 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.company`.
2024-07-27 05:15:06.869 DEBUG faker.factory:factory.py:95: Provider `faker.providers.company` has been localized to `en_US`.
2024-07-27 05:15:06.869 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2024-07-27 05:15:06.869 DEBUG faker.factory:factory.py:95: Provider `faker.providers.credit_card` has been localized to `en_US`.
2024-07-27 05:15:06.869 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.currency`.
2024-07-27 05:15:06.870 DEBUG faker.factory:factory.py:95: Provider `faker.providers.currency` has been localized to `en_US`.
2024-07-27 05:15:06.870 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.date_time`.
2024-07-27 05:15:06.871 DEBUG faker.factory:factory.py:95: Provider `faker.providers.date_time` has been localized to `en_US`.
2024-07-27 05:15:06.872 DEBUG faker.factory:factory.py:106: Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.872 DEBUG faker.factory:factory.py:106: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.872 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.geo`.
2024-07-27 05:15:06.872 DEBUG faker.factory:factory.py:95: Provider `faker.providers.geo` has been localized to `en_US`.
2024-07-27 05:15:06.873 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.internet`.
2024-07-27 05:15:06.874 DEBUG faker.factory:factory.py:95: Provider `faker.providers.internet` has been localized to `en_US`.
2024-07-27 05:15:06.875 DEBUG faker.factory:factory.py:106: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.875 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.job`.
2024-07-27 05:15:06.876 DEBUG faker.factory:factory.py:95: Provider `faker.providers.job` has been localized to `en_US`.
2024-07-27 05:15:06.876 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.lorem`.
2024-07-27 05:15:06.877 DEBUG faker.factory:factory.py:95: Provider `faker.providers.lorem` has been localized to `en_US`.
2024-07-27 05:15:06.877 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.misc`.
2024-07-27 05:15:06.877 DEBUG faker.factory:factory.py:95: Provider `faker.providers.misc` has been localized to `en_US`.
2024-07-27 05:15:06.878 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.passport`.
2024-07-27 05:15:06.878 DEBUG faker.factory:factory.py:95: Provider `faker.providers.passport` has been localized to `en_US`.
2024-07-27 05:15:06.878 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.person`.
2024-07-27 05:15:06.880 DEBUG faker.factory:factory.py:95: Provider `faker.providers.person` has been localized to `en_US`.
2024-07-27 05:15:06.880 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2024-07-27 05:15:06.882 DEBUG faker.factory:factory.py:95: Provider `faker.providers.phone_number` has been localized to `en_US`.
2024-07-27 05:15:06.883 DEBUG faker.factory:factory.py:106: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.883 DEBUG faker.factory:factory.py:106: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.883 DEBUG faker.factory:factory.py:106: Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.883 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.ssn`.
2024-07-27 05:15:06.884 DEBUG faker.factory:factory.py:95: Provider `faker.providers.ssn` has been localized to `en_US`.
2024-07-27 05:15:06.884 DEBUG faker.factory:factory.py:106: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-27 05:15:06.885 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-07-27 05:15:07.258 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "POST /backend/api/deal/create-with-client HTTP/1.1" 200 None
2024-07-27 05:15:07.258 CRITICAL root:helpers_api.py:27: ___response code- 200
2024-07-27 05:15:07.259 CRITICAL root:helpers_api.py:28: ___response body- {'deal_id': 5419}
2024-07-27 05:15:07.260 DEBUG tests_api.utils.logger:logger.py:23: > GET https://dev.agentum.pro/backend/api/deal/get-object-count-button/5419 {'method': 'GET', 'url': 'https://dev.agentum.pro/backend/api/deal/get-object-count-button/5419', 'params': None, 'headers': {'Authorization': 'Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz', 'Content-Type': 'application/json'}}
2024-07-27 05:15:07.261 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-07-27 05:15:08.082 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "GET /backend/api/deal/get-object-count-button/5419 HTTP/1.1" 200 None
2024-07-27 05:15:08.083 DEBUG tests_api.utils.logger:logger.py:27: < 200 https://dev.agentum.pro/backend/api/deal/get-object-count-button/5419 {"object_founded":45742}
2024-07-27 05:15:08.083 DEBUG tests_api.utils.logger:logger.py:35: curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz' -H 'Connection: keep-alive' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.31.0' https://dev.agentum.pro/backend/api/deal/get-object-count-button/5419
2024-07-27 05:15:08.083 INFO root:test_deals.py:154: <Response [200]>
2024-07-27 05:15:08.086 INFO fixture:conftest.py:63: Process ended